In [2]:
import pandas as pd

In [3]:
# Load the dataset
data = pd.read_csv('/kaggle/input/sgcc-dataset/datasetsmall.csv')
# data = pd.read_csv('/kaggle/input/sgcc-dataset/data set.csv')
new_cols=[]
for i in data.columns:
    if i[0]=='1':
        new_cols.append("0"+i)
    else :
        new_cols.append(i)

data.columns=new_cols
data

,01/01/2014,01/02/2014,01/03/2014,01/04/2014,01/05/2014,01/06/2014,01/07/2014,01/08/2014,01/09/2014,01/10/2014,...,01/19/2014,01/20/2014,01/21/2014,01/22/2014,01/23/2014,01/24/2014,01/25/2014,01/26/2014,CONS_NO,FLAG
0,2401.00,2500.00,2674.00,2432.00,2231.00,1942.00,2752.00,1244.00,2069.00,2360.00,...,1774.00,2089.00,1300.00,2419.00,2462.00,1177.00,340.00,2272.00,A0E791400CF1C48C43DC26A68227854A,1
1,3318.00,282.00,540.00,5670.00,4854.00,4170.00,4848.00,3546.00,4416.00,3966.00,...,3876.00,3228.00,3054.00,3840.00,1422.00,1956.00,1380.00,96.00,B415F931D3BFB17ACEF48BC648B04FC2,1
2,1020.80,1097.40,1377.40,1408.80,1414.80,1387.40,1444.60,1325.00,1461.60,1253.20,...,1214.60,1285.40,1279.60,1188.60,1362.60,1286.00,1267.60,1444.00,DE8E1EAE4E578C0CEF92D1E23499888F,1
3,0.00,1183.80,1190.40,1183.80,0.00,1154.40,1166.40,1183.80,1169.40,1174.20,...,0.00,1072.80,1090.80,1090.20,1101.00,1079.40,1121.40,1145.40,2952491E940C9040B188B3C9095910D6,0
4,1445.70,1348.20,1281.90,1276.35,1219.95,1289.85,1298.55,1326.15,1410.60,1376.70,...,1331.85,1392.90,1213.20,1463.10,1405.50,1240.05,1190.25,1455.45,DBEED8FD0E7F5E0D1BAF1F86F4983459,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25858,114.75,91.60,120.07,132.85,114.44,124.04,101.42,101.06,94.22,146.30,...,127.19,144.75,137.79,119.00,113.24,125.57,120.00,106.20,75B68BB33C5E9570705D551DED450E96,0
25859,0.00,107.20,97.80,85.40,0.00,0.00,0.00,0.00,0.00,0.00,...,112.50,150.40,0.00,134.70,0.00,0.00,75.80,0.00,522CD12E4FD07B23C55E2E2F475D4AB0,1
25860,148.40,159.86,157.20,104.80,118.17,176.44,171.94,171.19,168.89,174.02,...,0.00,119.24,106.21,115.07,131.66,104.25,103.04,75.75,970130CABEA2DD1B3C99E853331BC93F,0
25861,7.78,7.15,8.25,8.87,12.00,7.90,5.34,9.73,9.88,5.29,...,7.31,7.95,9.66,5.14,6.56,6.09,5.88,7.09,35244DA0EC3E6B58E3EF26CFF1D55CE1,1
25862,0.00,3.56,0.00,0.00,1.80,0.00,4.10,1.41,1.78,0.00,...,NaN,NaN,0.00,5.97,6.15,6.10,8.03,5.61,768309B0EB11FD436CEE5ABFB84F4C0C,1

In [4]:
# by row
df=data.drop('FLAG',axis=1)
df=df.apply(pd.DataFrame.describe, axis=1)
df['FLAG']=data['FLAG']
df

       count  unique      top  freq  FLAG
0       27.0    27.0  2401.00   1.0     1
1       27.0    27.0  3318.00   1.0     1
2       27.0    27.0  1020.80   1.0     1
3       27.0    21.0  1183.80   4.0     0
4       27.0    27.0  1445.70   1.0     1
...      ...     ...      ...   ...   ...
25858   27.0    27.0   114.75   1.0     0
25859   27.0    14.0     0.00  14.0     1
25860   27.0    23.0     0.00   5.0     0
25861   25.0    23.0     0.00   3.0     1
25862   20.0    14.0     0.00   7.0     1

[25863 rows x 5 columns]

In [8]:
! pip install sqlalchemy pg8000 --quiet

In [9]:
from sqlalchemy import create_engine, Column, Integer, String, Float, Boolean, Date, ForeignKey, Sequence
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship, sessionmaker

DB_HOST      = '35.222.242.8'
DB_PORT      = 5432
DB_NAME      = 'postgres'
DB_USER      = 'postgres'
DB_PASSWORD  = 'Namaganda.7'

DATABASE_URL = f'postgresql+pg8000://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}'
engine = create_engine(DATABASE_URL, echo=True)
Base = declarative_base()

class PowerMeter(Base):
    __tablename__ = 'power_meter'
    user_id = Column(Integer, Sequence('user_id_seq'), primary_key=True, autoincrement=True)
    location_longitude = Column(Float, nullable=False)
    location_latitude = Column(Float, nullable=False)
    district = Column(String(100), nullable=False)
    region = Column(String(100), nullable=False)
    
    power_values = relationship('PowerValues', back_populates='user')
    recent_power_values = relationship('RecentPowerValues', back_populates='user')
    anomaly_predictions = relationship('AnomalyPredictions', back_populates='user')

class PowerValues(Base):
    __tablename__ = 'power_values'
    id = Column(Integer, Sequence('power_values_id_seq'), primary_key=True, autoincrement=True)
    user_id = Column(Integer, ForeignKey('power_meter.user_id'), nullable=False)
    power_value = Column(Float, nullable=False)
    date_logged = Column(Date, nullable=False)
    
    user = relationship('PowerMeter', back_populates='power_values')

class RecentPowerValues(Base):
    __tablename__ = 'recent_power_values'
    id = Column(Integer, Sequence('recent_power_values_id_seq'), primary_key=True, autoincrement=True)
    user_id = Column(Integer, ForeignKey('power_meter.user_id'), nullable=False)
    power_value = Column(String, nullable=False)
    date_logged = Column(Date, nullable=False)
    
    user = relationship('PowerMeter', back_populates='recent_power_values')

class AnomalyPredictions(Base):
    __tablename__ = 'anomaly_predictions'
    id = Column(Integer, Sequence('anomaly_predictions_id_seq'), primary_key=True, autoincrement=True)
    user_id = Column(Integer, ForeignKey('power_meter.user_id'), nullable=False)
    anomaly = Column(Boolean, nullable=False)
    date_predicted = Column(Date, nullable=False)
    
    user = relationship('PowerMeter', back_populates='anomaly_predictions')

/tmp/ipykernel_32/3507389786.py:13: MovedIn20Warning: The ``declarative_base()`` function is now available as sqlalchemy.orm.declarative_base(). (deprecated since: 2.0) (Background on SQLAlchemy 2.0 at: https://sqlalche.me/e/b8d9)
  Base = declarative_base()

In [11]:
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)
mySession = SessionLocal()

In [43]:
columns = [x for x in data]
columns

['01/01/2014',
 '01/02/2014',
 '01/03/2014',
 '01/04/2014',
 '01/05/2014',
 '01/06/2014',
 '01/07/2014',
 '01/08/2014',
 '01/09/2014',
 '01/10/2014',
 '01/11/2014',
 '01/12/2014',
 '01/13/2014',
 '01/14/2014',
 '01/15/2014',
 '01/16/2014',
 '01/17/2014',
 '01/18/2014',
 '01/19/2014',
 '01/20/2014',
 '01/21/2014',
 '01/22/2014',
 '01/23/2014',
 '01/24/2014',
 '01/25/2014',
 '01/26/2014',
 'CONS_NO',
 'FLAG']

In [33]:
dd = data.to_csv('data.csv')
with open('data.csv','r') as file:
    line = file.readline()
    print(line)

,01/01/2014,01/02/2014,01/03/2014,01/04/2014,01/05/2014,01/06/2014,01/07/2014,01/08/2014,01/09/2014,01/10/2014,01/11/2014,01/12/2014,01/13/2014,01/14/2014,01/15/2014,01/16/2014,01/17/2014,01/18/2014,01/19/2014,01/20/2014,01/21/2014,01/22/2014,01/23/2014,01/24/2014,01/25/2014,01/26/2014,CONS_NO,FLAG

In [59]:
import datetime as dt

In [62]:
mySession.rollback()

/tmp/ipykernel_32/589873732.py:1: SAWarning: Session's state has been changed on a non-active transaction - this state will be discarded.
  mySession.rollback()

In [ ]:
with open('data.csv','r') as file:
    line = file.readline()
    for i in range(len(data)):
        line = file.readline().split(',')
        recent = PowerMeter(
            user_id = i+1,
            location_longitude = 32.5816,
            location_latitude = 0.3152,
            district = 'Kampala',
            region = line[-2],
            
        )
        mySession.add(recent)
        mySession.commit()

2024-07-21 10:20:16,395 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-07-21 10:20:16,398 INFO sqlalchemy.engine.Engine INSERT INTO power_meter (user_id, location_longitude, location_latitude, district, region) VALUES (%s::INTEGER, %s::FLOAT, %s::FLOAT, %s::VARCHAR, %s::VARCHAR)
2024-07-21 10:20:16,400 INFO sqlalchemy.engine.Engine [generated in 0.00152s] (1, 32.5816, 0.3152, 'Kampala', 'A0E791400CF1C48C43DC26A68227854A')
2024-07-21 10:20:16,564 INFO sqlalchemy.engine.Engine COMMIT
2024-07-21 10:20:16,676 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-07-21 10:20:16,677 INFO sqlalchemy.engine.Engine INSERT INTO power_meter (user_id, location_longitude, location_latitude, district, region) VALUES (%s::INTEGER, %s::FLOAT, %s::FLOAT, %s::VARCHAR, %s::VARCHAR)
2024-07-21 10:20:16,679 INFO sqlalchemy.engine.Engine [cached since 0.2804s ago] (2, 32.5816, 0.3152, 'Kampala', 'B415F931D3BFB17ACEF48BC648B04FC2')
2024-07-21 10:20:16,825 INFO sqlalchemy.engine.Engine COMMIT
2024-07-21 10:20:16,937 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-07-21 10:20:16,939 INFO sqlalchemy.engine.Engine INSERT INTO power_meter (user_id, location_longitude, location_latitude, district, region) VALUES (%s::INTEGER, %s::FLOAT, %s::FLOAT, %s::VARCHAR, %s::VARCHAR)
2024-07-21 10:20:16,940 INFO sqlalchemy.engine.Engine [cached since 0.5419s ago] (3, 32.5816, 0.3152, 'Kampala', 'DE8E1EAE4E578C0CEF92D1E23499888F')
2024-07-21 10:20:17,087 INFO sqlalchemy.engine.Engine COMMIT
2024-07-21 10:20:17,199 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-07-21 10:20:17,200 INFO sqlalchemy.engine.Engine INSERT INTO power_meter (user_id, location_longitude, location_latitude, district, region) VALUES (%s::INTEGER, %s::FLOAT, %s::FLOAT, %s::VARCHAR, %s::VARCHAR)
2024-07-21 10:20:17,201 INFO sqlalchemy.engine.Engine [cached since 0.8031s ago] (4, 32.5816, 0.3152, 'Kampala', '2952491E940C9040B188B3C9095910D6')
2024-07-21 10:20:17,348 INFO sqlalchemy.engine.Engine COMMIT
2024-07-21 10:20:17,460 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-07-21 10:20:17,461 INFO sqlalchemy.engine.Engine INSERT INTO power_meter (user_id, location_longitude, location_latitude, district, region) VALUES (%s::INTEGER, %s::FLOAT, %s::FLOAT, %s::VARCHAR, %s::VARCHAR)
2024-07-21 10:20:17,463 INFO sqlalchemy.engine.Engine [cached since 1.064s ago] (5, 32.5816, 0.3152, 'Kampala', 'DBEED8FD0E7F5E0D1BAF1F86F4983459')
2024-07-21 10:20:17,610 INFO sqlalchemy.engine.Engine COMMIT
2024-07-21 10:20:17,721 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-07-21 10:20:17,723 INFO sqlalchemy.engine.Engine INSERT INTO power_meter (user_id, location_longitude, location_latitude, district, region) VALUES (%s::INTEGER, %s::FLOAT, %s::FLOAT, %s::VARCHAR, %s::VARCHAR)
2024-07-21 10:20:17,724 INFO sqlalchemy.engine.Engine [cached since 1.325s ago] (6, 32.5816, 0.3152, 'Kampala', '9495BA31FC50C86D827FE1D5B1D8773B')
2024-07-21 10:20:17,871 INFO sqlalchemy.engine.Engine COMMIT
2024-07-21 10:20:17,983 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-07-21 10:20:17,984 INFO sqlalchemy.engine.Engine INSERT INTO power_meter (user_id, location_longitude, location_latitude, district, region) VALUES (%s::INTEGER, %s::FLOAT, %s::FLOAT, %s::VARCHAR, %s::VARCHAR)
2024-07-21 10:20:17,985 INFO sqlalchemy.engine.Engine [cached since 1.587s ago] (7, 32.5816, 0.3152, 'Kampala', '58A9AA93B0455CE70D447B13CAF9876E')
2024-07-21 10:20:18,132 INFO sqlalchemy.engine.Engine COMMIT
2024-07-21 10:20:18,243 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-07-21 10:20:18,245 INFO sqlalchemy.engine.Engine INSERT INTO power_meter (user_id, location_longitude, location_latitude, district, region) VALUES (%s::INTEGER, %s::FLOAT, %s::FLOAT, %s::VARCHAR, %s::VARCHAR)
2024-07-21 10:20:18,246 INFO sqlalchemy.engine.Engine [cached since 1.848s ago] (8, 32.5816, 0.3152, 'Kampala', '1BC425A74948B48CED2DD171224E219C')
2024-07-21 10:20:18,393 INFO sqlalchemy.engine.Engine COMMIT
2024-07-21 10:20:18,506 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-07-21 10:20:18,508 INFO sqlalchemy.engine.Engine INSERT INTO power_meter (user_id, location_longitude, location_latitude, district, region) VALUES (%s::INTEGER, %s::FLOAT, %s::FLOAT, %s::VARCHAR, %s::VARCHAR)
2024-07-21 10:20:18,509 INFO sqlalchemy.engine.Engine [cached since 2.11s ago] (9, 32.5816, 0.3152, 'Kampala', '231B2821E4D98BBFF9E3E111D391ECF5')
2024-07-21 10:20:18,655 INFO sqlalchemy.engine.Engine COMMIT
2024-07-21 10:20:18,767 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-07-21 10:20:18,769 INFO sqlalchemy.engine.Engine INSERT INTO power_meter (user_id, location_longitude, location_latitude, district, region) VALUES (%s::INTEGER, %s::FLOAT, %s::FLOAT, %s::VARCHAR, %s::VARCHAR)
2024-07-21 10:20:18,770 INFO sqlalchemy.engine.Engine [cached since 2.372s ago] (10, 32.5816, 0.3152, 'Kampala', 'E24AC6F28F330CCDBAEAFCD82E86609B')
2024-07-21 10:20:18,916 INFO sqlalchemy.engine.Engine COMMIT
2024-07-21 10:20:19,028 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-07-21 10:20:19,029 INFO sqlalchemy.engine.Engine INSERT INTO power_meter (user_id, location_longitude, location_latitude, district, region) VALUES (%s::INTEGER, %s::FLOAT, %s::FLOAT, %s::VARCHAR, %s::VARCHAR)
2024-07-21 10:20:19,030 INFO sqlalchemy.engine.Engine [cached since 2.632s ago] (11, 32.5816, 0.3152, 'Kampala', 'B863662FFE6AF2272F5E9749C6CFC0AC')
2024-07-21 10:20:19,177 INFO sqlalchemy.engine.Engine COMMIT
2024-07-21 10:20:19,288 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-07-21 10:20:19,290 INFO sqlalchemy.engine.Engine INSERT INTO power_meter (user_id, location_longitude, location_latitude, district, region) VALUES (%s::INTEGER, %s::FLOAT, %s::FLOAT, %s::VARCHAR, %s::VARCHAR)
2024-07-21 10:20:19,291 INFO sqlalchemy.engine.Engine [cached since 2.892s ago] (12, 32.5816, 0.3152, 'Kampala', '30C62896BD4C8E9C95323A6867974C18')
2024-07-21 10:20:19,438 INFO sqlalchemy.engine.Engine COMMIT
2024-07-21 10:20:19,549 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-07-21 10:20:19,551 INFO sqlalchemy.engine.Engine INSERT INTO power_meter (user_id, location_longitude, location_latitude, district, region) VALUES (%s::INTEGER, %s::FLOAT, %s::FLOAT, %s::VARCHAR, %s::VARCHAR)
2024-07-21 10:20:19,552 INFO sqlalchemy.engine.Engine [cached since 3.154s ago] (13, 32.5816, 0.3152, 'Kampala', 'CC20362FC534A57BB37B84F009106947')
2024-07-21 10:20:19,699 INFO sqlalchemy.engine.Engine COMMIT
2024-07-21 10:20:19,810 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-07-21 10:20:19,812 INFO sqlalchemy.engine.Engine INSERT INTO power_meter (user_id, location_longitude, location_latitude, district, region) VALUES (%s::INTEGER, %s::FLOAT, %s::FLOAT, %s::VARCHAR, %s::VARCHAR)
2024-07-21 10:20:19,813 INFO sqlalchemy.engine.Engine [cached since 3.415s ago] (14, 32.5816, 0.3152, 'Kampala', '67401768ADEDE27B28C2FC9B397AF0BA')
2024-07-21 10:20:19,961 INFO sqlalchemy.engine.Engine COMMIT
2024-07-21 10:20:20,072 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-07-21 10:20:20,074 INFO sqlalchemy.engine.Engine INSERT INTO power_meter (user_id, location_longitude, location_latitude, district, region) VALUES (%s::INTEGER, %s::FLOAT, %s::FLOAT, %s::VARCHAR, %s::VARCHAR)
2024-07-21 10:20:20,075 INFO sqlalchemy.engine.Engine [cached since 3.677s ago] (15, 32.5816, 0.3152, 'Kampala', '9575A8D9320263231F17ADDB8E01A093')
2024-07-21 10:20:20,222 INFO sqlalchemy.engine.Engine COMMIT
2024-07-21 10:20:20,335 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-07-21 10:20:20,336 INFO sqlalchemy.engine.Engine INSERT INTO power_meter (user_id, location_longitude, location_latitude, district, region) VALUES (%s::INTEGER, %s::FLOAT, %s::FLOAT, %s::VARCHAR, %s::VARCHAR)
2024-07-21 10:20:20,337 INFO sqlalchemy.engine.Engine [cached since 3.939s ago] (16, 32.5816, 0.3152, 'Kampala', 'E32A293853BF871F058FAFB707D4C183')
2024-07-21 10:20:20,483 INFO sqlalchemy.engine.Engine COMMIT
2024-07-21 10:20:20,595 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-07-21 10:20:20,597 INFO sqlalchemy.engine.Engine INSERT INTO power_meter (user_id, location_longitude, location_latitude, district, region) VALUES (%s::INTEGER, %s::FLOAT, %s::FLOAT, %s::VARCHAR, %s::VARCHAR)
2024-07-21 10:20:20,598 INFO sqlalchemy.engine.Engine [cached since 4.2s ago] (17, 32.5816, 0.3152, 'Kampala', 'DB57CB0C40DC400C6D3365E306280B79')
2024-07-21 10:20:20,745 INFO sqlalchemy.engine.Engine COMMIT
2024-07-21 10:20:20,857 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-07-21 10:20:20,858 INFO sqlalchemy.engine.Engine INSERT INTO power_meter (user_id, location_longitude, location_latitude, district, region) VALUES (%s::INTEGER, %s::FLOAT, %s::FLOAT, %s::VARCHAR, %s::VARCHAR)
2024-07-21 10:20:20,859 INFO sqlalchemy.engine.Engine [cached since 4.461s ago] (18, 32.5816, 0.3152, 'Kampala', '1B173C1A3A2EEF026D089EE150A5AA51')
2024-07-21 10:20:21,006 INFO sqlalchemy.engine.Engine COMMIT
2024-07-21 10:20:21,118 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-07-21 10:20:21,119 INFO sqlalchemy.engine.Engine INSERT INTO power_meter (user_id, location_longitude, location_latitude, district, region) VALUES (%s::INTEGER, %s::FLOAT, %s::FLOAT, %s::VARCHAR, %s::VARCHAR)
2024-07-21 10:20:21,120 INFO sqlalchemy.engine.Engine [cached since 4.722s ago] (19, 32.5816, 0.3152, 'Kampala', 'A87D17DE90DA14049F54A9400B6D2E1B')
2024-07-21 10:20:21,267 INFO sqlalchemy.engine.Engine COMMIT
2024-07-21 10:20:21,379 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-07-21 10:20:21,380 INFO sqlalchemy.engine.Engine INSERT INTO power_meter (user_id, location_longitude, location_latitude, district, region) VALUES (%s::INTEGER, %s::FLOAT, %s::FLOAT, %s::VARCHAR, %s::VARCHAR)
2024-07-21 10:20:21,381 INFO sqlalchemy.engine.Engine [cached since 4.983s ago] (20, 32.5816, 0.3152, 'Kampala', 'E366A01D354E862F928E723201718E0D')
2024-07-21 10:20:21,528 INFO sqlalchemy.engine.Engine COMMIT
2024-07-21 10:20:21,640 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-07-21 10:20:21,641 INFO sqlalchemy.engine.Engine INSERT INTO power_meter (user_id, location_longitude, location_latitude, district, region) VALUES (%s::INTEGER, %s::FLOAT, %s::FLOAT, %s::VARCHAR, %s::VARCHAR)
2024-07-21 10:20:21,642 INFO sqlalchemy.engine.Engine [cached since 5.244s ago] (21, 32.5816, 0.3152, 'Kampala', '3CC8959A5C90F8B6F58242FEB03796B9')
2024-07-21 10:20:21,789 INFO sqlalchemy.engine.Engine COMMIT
2024-07-21 10:20:21,900 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-07-21 10:20:21,902 INFO sqlalchemy.engine.Engine INSERT INTO power_meter (user_id, location_longitude, location_latitude, district, region) VALUES (%s::INTEGER, %s::FLOAT, %s::FLOAT, %s::VARCHAR, %s::VARCHAR)
2024-07-21 10:20:21,903 INFO sqlalchemy.engine.Engine [cached since 5.505s ago] (22, 32.5816, 0.3152, 'Kampala', '397C84F9F2AEF73869F12D82B3D54DE3')
2024-07-21 10:20:22,049 INFO sqlalchemy.engine.Engine COMMIT
2024-07-21 10:20:22,161 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-07-21 10:20:22,163 INFO sqlalchemy.engine.Engine INSERT INTO power_meter (user_id, location_longitude, location_latitude, district, region) VALUES (%s::INTEGER, %s::FLOAT, %s::FLOAT, %s::VARCHAR, %s::VARCHAR)
2024-07-21 10:20:22,164 INFO sqlalchemy.engine.Engine [cached since 5.765s ago] (23, 32.5816, 0.3152, 'Kampala', '3EAD6E3B0349CDF3DA50036BDA8D3526')
2024-07-21 10:20:22,310 INFO sqlalchemy.engine.Engine COMMIT
2024-07-21 10:20:22,423 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-07-21 10:20:22,424 INFO sqlalchemy.engine.Engine INSERT INTO power_meter (user_id, location_longitude, location_latitude, district, region) VALUES (%s::INTEGER, %s::FLOAT, %s::FLOAT, %s::VARCHAR, %s::VARCHAR)
2024-07-21 10:20:22,425 INFO sqlalchemy.engine.Engine [cached since 6.027s ago] (24, 32.5816, 0.3152, 'Kampala', '9B673D1E56E2E1A879CD2FF23A1AEE00')
2024-07-21 10:20:22,572 INFO sqlalchemy.engine.Engine COMMIT
2024-07-21 10:20:22,684 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-07-21 10:20:22,686 INFO sqlalchemy.engine.Engine INSERT INTO power_meter (user_id, location_longitude, location_latitude, district, region) VALUES (%s::INTEGER, %s::FLOAT, %s::FLOAT, %s::VARCHAR, %s::VARCHAR)
2024-07-21 10:20:22,687 INFO sqlalchemy.engine.Engine [cached since 6.289s ago] (25, 32.5816, 0.3152, 'Kampala', '48A51E0A570E113AA1AAC366107474AB')
2024-07-21 10:20:22,834 INFO sqlalchemy.engine.Engine COMMIT
2024-07-21 10:20:22,946 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-07-21 10:20:22,947 INFO sqlalchemy.engine.Engine INSERT INTO power_meter (user_id, location_longitude, location_latitude, district, region) VALUES (%s::INTEGER, %s::FLOAT, %s::FLOAT, %s::VARCHAR, %s::VARCHAR)
2024-07-21 10:20:22,948 INFO sqlalchemy.engine.Engine [cached since 6.55s ago] (26, 32.5816, 0.3152, 'Kampala', '4205BD81A160815DFFF2EC4EA72D2A77')
2024-07-21 10:20:23,095 INFO sqlalchemy.engine.Engine COMMIT
2024-07-21 10:20:23,207 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-07-21 10:20:23,208 INFO sqlalchemy.engine.Engine INSERT INTO power_meter (user_id, location_longitude, location_latitude, district, region) VALUES (%s::INTEGER, %s::FLOAT, %s::FLOAT, %s::VARCHAR, %s::VARCHAR)
2024-07-21 10:20:23,209 INFO sqlalchemy.engine.Engine [cached since 6.811s ago] (27, 32.5816, 0.3152, 'Kampala', '82B5C45A4D4CA08B4AFE134A29ED33B3')
2024-07-21 10:20:23,356 INFO sqlalchemy.engine.Engine COMMIT
2024-07-21 10:20:23,468 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-07-21 10:20:23,469 INFO sqlalchemy.engine.Engine INSERT INTO power_meter (user_id, location_longitude, location_latitude, district, region) VALUES (%s::INTEGER, %s::FLOAT, %s::FLOAT, %s::VARCHAR, %s::VARCHAR)
2024-07-21 10:20:23,470 INFO sqlalchemy.engine.Engine [cached since 7.072s ago] (28, 32.5816, 0.3152, 'Kampala', '6BE479A4474BF6DA432D7528CF4B50D2')
2024-07-21 10:20:23,618 INFO sqlalchemy.engine.Engine COMMIT
2024-07-21 10:20:23,730 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-07-21 10:20:23,731 INFO sqlalchemy.engine.Engine INSERT INTO power_meter (user_id, location_longitude, location_latitude, district, region) VALUES (%s::INTEGER, %s::FLOAT, %s::FLOAT, %s::VARCHAR, %s::VARCHAR)
2024-07-21 10:20:23,733 INFO sqlalchemy.engine.Engine [cached since 7.334s ago] (29, 32.5816, 0.3152, 'Kampala', '8FA8003CAAB6DE406E70642E64A24E8E')
2024-07-21 10:20:23,879 INFO sqlalchemy.engine.Engine COMMIT
2024-07-21 10:20:23,991 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-07-21 10:20:23,992 INFO sqlalchemy.engine.Engine INSERT INTO power_meter (user_id, location_longitude, location_latitude, district, region) VALUES (%s::INTEGER, %s::FLOAT, %s::FLOAT, %s::VARCHAR, %s::VARCHAR)
2024-07-21 10:20:23,993 INFO sqlalchemy.engine.Engine [cached since 7.595s ago] (30, 32.5816, 0.3152, 'Kampala', '1BA56D68B7E76F48354F8C4BDC8ECBF0')
2024-07-21 10:20:24,140 INFO sqlalchemy.engine.Engine COMMIT
2024-07-21 10:20:24,253 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-07-21 10:20:24,254 INFO sqlalchemy.engine.Engine INSERT INTO power_meter (user_id, location_longitude, location_latitude, district, region) VALUES (%s::INTEGER, %s::FLOAT, %s::FLOAT, %s::VARCHAR, %s::VARCHAR)
2024-07-21 10:20:24,255 INFO sqlalchemy.engine.Engine [cached since 7.857s ago] (31, 32.5816, 0.3152, 'Kampala', 'B7166CB3F6008392C3EA0061C6B1C5F0')
2024-07-21 10:20:24,402 INFO sqlalchemy.engine.Engine COMMIT
2024-07-21 10:20:24,514 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-07-21 10:20:24,516 INFO sqlalchemy.engine.Engine INSERT INTO power_meter (user_id, location_longitude, location_latitude, district, region) VALUES (%s::INTEGER, %s::FLOAT, %s::FLOAT, %s::VARCHAR, %s::VARCHAR)
2024-07-21 10:20:24,517 INFO sqlalchemy.engine.Engine [cached since 8.118s ago] (32, 32.5816, 0.3152, 'Kampala', '951D5DC7EB787F937C831E9002755C51')
2024-07-21 10:20:24,663 INFO sqlalchemy.engine.Engine COMMIT
2024-07-21 10:20:24,776 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-07-21 10:20:24,777 INFO sqlalchemy.engine.Engine INSERT INTO power_meter (user_id, location_longitude, location_latitude, district, region) VALUES (%s::INTEGER, %s::FLOAT, %s::FLOAT, %s::VARCHAR, %s::VARCHAR)
2024-07-21 10:20:24,778 INFO sqlalchemy.engine.Engine [cached since 8.38s ago] (33, 32.5816, 0.3152, 'Kampala', 'E00F9C5061BFC7C81AEDA65DB0381B21')
2024-07-21 10:20:24,925 INFO sqlalchemy.engine.Engine COMMIT
2024-07-21 10:20:25,037 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-07-21 10:20:25,038 INFO sqlalchemy.engine.Engine INSERT INTO power_meter (user_id, location_longitude, location_latitude, district, region) VALUES (%s::INTEGER, %s::FLOAT, %s::FLOAT, %s::VARCHAR, %s::VARCHAR)
2024-07-21 10:20:25,040 INFO sqlalchemy.engine.Engine [cached since 8.642s ago] (34, 32.5816, 0.3152, 'Kampala', '6464E5491E27D1F5C260A94DDE4DDF24')
2024-07-21 10:20:25,187 INFO sqlalchemy.engine.Engine COMMIT
2024-07-21 10:20:25,302 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-07-21 10:20:25,304 INFO sqlalchemy.engine.Engine INSERT INTO power_meter (user_id, location_longitude, location_latitude, district, region) VALUES (%s::INTEGER, %s::FLOAT, %s::FLOAT, %s::VARCHAR, %s::VARCHAR)
2024-07-21 10:20:25,305 INFO sqlalchemy.engine.Engine [cached since 8.907s ago] (35, 32.5816, 0.3152, 'Kampala', '2A81B03ED5351943CA5A321D90E48311')
2024-07-21 10:20:25,452 INFO sqlalchemy.engine.Engine COMMIT
2024-07-21 10:20:25,564 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-07-21 10:20:25,566 INFO sqlalchemy.engine.Engine INSERT INTO power_meter (user_id, location_longitude, location_latitude, district, region) VALUES (%s::INTEGER, %s::FLOAT, %s::FLOAT, %s::VARCHAR, %s::VARCHAR)
2024-07-21 10:20:25,567 INFO sqlalchemy.engine.Engine [cached since 9.169s ago] (36, 32.5816, 0.3152, 'Kampala', '3C2CCB2FA382CFB6D94BA9695A9E65C9')
2024-07-21 10:20:25,714 INFO sqlalchemy.engine.Engine COMMIT
2024-07-21 10:20:25,826 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-07-21 10:20:25,827 INFO sqlalchemy.engine.Engine INSERT INTO power_meter (user_id, location_longitude, location_latitude, district, region) VALUES (%s::INTEGER, %s::FLOAT, %s::FLOAT, %s::VARCHAR, %s::VARCHAR)
2024-07-21 10:20:25,828 INFO sqlalchemy.engine.Engine [cached since 9.43s ago] (37, 32.5816, 0.3152, 'Kampala', '2A52ED1A0FC04FA0FE673D2733D530E4')
2024-07-21 10:20:25,976 INFO sqlalchemy.engine.Engine COMMIT
2024-07-21 10:20:26,088 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-07-21 10:20:26,089 INFO sqlalchemy.engine.Engine INSERT INTO power_meter (user_id, location_longitude, location_latitude, district, region) VALUES (%s::INTEGER, %s::FLOAT, %s::FLOAT, %s::VARCHAR, %s::VARCHAR)
2024-07-21 10:20:26,090 INFO sqlalchemy.engine.Engine [cached since 9.692s ago] (38, 32.5816, 0.3152, 'Kampala', '69F2A91828B2DCF2B69AD3C77900DACA')
2024-07-21 10:20:26,237 INFO sqlalchemy.engine.Engine COMMIT
2024-07-21 10:20:26,349 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-07-21 10:20:26,351 INFO sqlalchemy.engine.Engine INSERT INTO power_meter (user_id, location_longitude, location_latitude, district, region) VALUES (%s::INTEGER, %s::FLOAT, %s::FLOAT, %s::VARCHAR, %s::VARCHAR)
2024-07-21 10:20:26,353 INFO sqlalchemy.engine.Engine [cached since 9.954s ago] (39, 32.5816, 0.3152, 'Kampala', '22A39B35F8923295CBCCF6EB1673422F')
2024-07-21 10:20:26,500 INFO sqlalchemy.engine.Engine COMMIT
2024-07-21 10:20:26,613 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-07-21 10:20:26,614 INFO sqlalchemy.engine.Engine INSERT INTO power_meter (user_id, location_longitude, location_latitude, district, region) VALUES (%s::INTEGER, %s::FLOAT, %s::FLOAT, %s::VARCHAR, %s::VARCHAR)
2024-07-21 10:20:26,615 INFO sqlalchemy.engine.Engine [cached since 10.22s ago] (40, 32.5816, 0.3152, 'Kampala', 'D69F76AF13C08FDF654216FAECCE9ACE')
2024-07-21 10:20:26,762 INFO sqlalchemy.engine.Engine COMMIT
2024-07-21 10:20:26,888 INFO sqlalchemy.engine.Engine BEGIN (implicit)

In [ ]:
with open('data.csv','r') as file:
    line = file.readline()
    for i in range(len(data)):
        line = file.readline().split(',')
        recent = RecentPowerValues(
            user_id = i+1,
            power_value = str(line[1:-2]),
            date_logged = dt.datetime.now()
            
        )
        mySession.add(recent)
        mySession.commit()